gems:
  - jekyll-redirect-from

version:
  - 2.3.1

version_v1:
  - 1.2.4

commitURL:
  - "https://github.com/vt-middleware/ldaptive/commit/"

issueURL:
  - "https://github.com/vt-middleware/ldaptive/issues/"

gIssueURL:
  - "https://code.google.com/p/vt-middleware/issues/detail?id="

